const flipkartData = {
  electronics: [
    { id: 1, name: 'IPhone 16', description: 'A budget smartphone with a great camera.', price: 10000, rating: 4.3, imageUrl: 'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/iphone-16-pro-finish-select-202409-6-3inch-blacktitanium?wid=5120&hei=2880&fmt=webp', url: 'https://www.flipkart.com' },
    { id: 2, name: 'Samsung Galaxy S23', description: 'A premium smartphone with excellent battery life.', price: 85000, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Galaxy+S23', url: 'https://www.flipkart.com' },
    { id: 3, name: 'OnePlus Nord CE 3', description: 'A mid-range smartphone with premium features.', price: 30000, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Nord+CE+3', url: 'https://www.flipkart.com' },
    { id: 4, name: 'Redmi Note 12', description: 'Affordable smartphone with high-speed performance.', price: 15000, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Note+12', url: 'https://www.flipkart.com' },
    { id: 5, name: 'Realme Narzo 60X', description: 'A gaming smartphone with long battery life.', price: 18000, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Narzo+60X', url: 'https://www.flipkart.com' },
    { id: 6, name: 'Apple AirPods Pro', description: 'Premium wireless earbuds with active noise cancellation.', price: 25000, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=AirPods+Pro', url: 'https://www.flipkart.com' },
    { id: 7, name: 'Dell Inspiron 3505', description: 'A lightweight laptop for daily productivity.', price: 45000, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Dell+Inspiron+3505', url: 'https://www.flipkart.com' },
    { id: 8, name: 'HP Envy x360', description: 'A powerful 2-in-1 convertible laptop.', price: 80000, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=HP+Envy+x360', url: 'https://www.flipkart.com' },
    { id: 9, name: 'Sony WH-1000XM5', description: 'Top-tier noise-canceling headphones.', price: 30000, rating: 4.9, imageUrl: 'https://via.placeholder.com/150?text=Sony+WH-1000XM5', url: 'https://www.flipkart.com' },
    { id: 10, name: 'Samsung Smart TV', description: 'A 4K UHD Smart TV with crystal-clear visuals.', price: 50000, rating: 4.8, imageUrl: 'https://via.placeholder.com/150?text=Samsung+Smart+TV', url: 'https://www.flipkart.com' },
    //  remaining products...
    ],
    jewelry: [
      { id: 1, name: 'Gold Necklace', description: 'Beautiful gold necklace with intricate designs.', price: 25000, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Gold+Necklace', url: 'https://www.flipkart.com' },
      { id: 2, name: 'Diamond Earrings', description: 'Sparkling diamond earrings with a modern design.', price: 50000, rating: 4.8, imageUrl: 'https://via.placeholder.com/150?text=Diamond+Earrings', url: 'https://www.flipkart.com' },
      { id: 3, name: 'Silver Bracelet', description: 'Elegant silver bracelet for daily wear.', price: 2000, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Silver+Bracelet', url: 'https://www.flipkart.com' },
      { id: 4, name: 'Platinum Ring', description: 'Premium platinum ring with a solitaire diamond.', price: 60000, rating: 4.9, imageUrl: 'https://via.placeholder.com/150?text=Platinum+Ring', url: 'https://www.flipkart.com' },
      { id: 5, name: 'Pearl Necklace', description: 'Classic pearl necklace with an elegant finish.', price: 8000, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Pearl+Necklace', url: 'https://www.flipkart.com' },
      { id: 6, name: 'Gold Bangles', description: 'Traditional gold bangles with intricate patterns.', price: 30000, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Gold+Bangles', url: 'https://www.flipkart.com' },
      { id: 7, name: 'Diamond Pendant', description: 'Stunning diamond pendant for special occasions.', price: 45000, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Diamond+Pendant', url: 'https://www.flipkart.com' },
      { id: 8, name: 'Ruby Ring', description: 'Elegant ring featuring a radiant ruby.', price: 22000, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Ruby+Ring', url: 'https://www.flipkart.com' },
      { id: 9, name: 'Silver Anklet', description: 'Delicate silver anklet with a modern touch.', price: 1200, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Silver+Anklet', url: 'https://www.flipkart.com' },
      { id: 10, name: 'Gold Chain', description: 'Simple and elegant gold chain for daily wear.', price: 15000, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Gold+Chain', url: 'https://www.flipkart.com' },
      //  remaining products...
    ],
    men_clothing: [
      { id: 1, name: 'Cotton T-Shirt', description: 'Comfortable T-shirt made of high-quality cotton.', price: 500, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Cotton+T-Shirt', url: 'https://www.flipkart.com' },
      { id: 2, name: 'Formal Shirt', description: 'Slim-fit formal shirt perfect for office wear.', price: 1000, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Formal+Shirt', url: 'https://www.flipkart.com' },
      { id: 3, name: 'Casual Jeans', description: 'Trendy and comfortable casual jeans.', price: 1500, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Casual+Jeans', url: 'https://www.flipkart.com' },
      { id: 4, name: 'Blazer', description: 'Elegant blazer for formal occasions.', price: 5000, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Blazer', url: 'https://www.flipkart.com' },
      { id: 5, name: 'Track Pants', description: 'Perfect track pants for workouts and casual wear.', price: 800, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Track+Pants', url: 'https://www.flipkart.com' },
      { id: 6, name: 'Hoodie', description: 'Comfortable hoodie for winters.', price: 1200, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Hoodie', url: 'https://www.flipkart.com' },
      { id: 7, name: 'Kurta', description: 'Traditional kurta for festive occasions.', price: 2000, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Kurta', url: 'https://www.flipkart.com' },
      { id: 8, name: 'Chinos', description: 'Stylish chinos with a tailored fit.', price: 1800, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Chinos', url: 'https://www.flipkart.com' },
      { id: 9, name: 'Polo T-Shirt', description: 'Classic polo T-shirt for casual outings.', price: 700, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Polo+T-Shirt', url: 'https://www.flipkart.com' },
      { id: 10, name: 'Leather Jacket', description: 'Premium leather jacket for a rugged look.', price: 8000, rating: 4.8, imageUrl: 'https://via.placeholder.com/150?text=Leather+Jacket', url: 'https://www.flipkart.com' },
      //  remaining 20 products...
    ],
    women_clothing: [
      { id: 1, name: 'Evening Gown', description: 'An elegant evening gown suitable for special occasions.', price: 4000, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Evening+Gown', url: 'https://www.flipkart.com' },
      { id: 2, name: 'Anarkali Suit', description: 'Traditional Anarkali suit with intricate embroidery.', price: 2500, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Anarkali+Suit', url: 'https://www.flipkart.com' },
      { id: 3, name: 'Denim Jacket', description: 'Stylish denim jacket for a casual look.', price: 1800, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Denim+Jacket', url: 'https://www.flipkart.com' },
      { id: 4, name: 'Kurti', description: 'Comfortable cotton kurti for daily wear.', price: 1000, rating: 4.3, imageUrl: 'https://m.media-amazon.com/images/I/518+mXFfoUL._AC_UY350_.jpg', url: 'https://www.flipkart.com' },
      { id: 5, name: 'Saree', description: 'Elegant saree with traditional motifs.', price: 3500, rating: 4.8, imageUrl: 'https://via.placeholder.com/150?text=Saree', url: 'https://www.flipkart.com' },
      { id: 6, name: 'Palazzo Pants', description: 'Trendy palazzo pants for casual wear.', price: 900, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Palazzo+Pants', url: 'https://www.flipkart.com' },
      { id: 7, name: 'Maxi Dress', description: 'Flowy maxi dress with a floral design.', price: 3000, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Maxi+Dress', url: 'https://www.flipkart.com' },
      { id: 8, name: 'Lehenga Choli', description: 'Traditional lehenga choli with vibrant colors.', price: 8000, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Lehenga+Choli', url: 'https://www.flipkart.com' },
      { id: 9, name: 'Formal Blouse', description: 'Chic blouse for office wear.', price: 1200, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Formal+Blouse', url: 'https://www.flipkart.com' },
      { id: 10, name: 'Woolen Sweater', description: 'Warm woolen sweater for winters.', price: 1500, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Woolen+Sweater', url: 'https://www.flipkart.com' },
      // remaining 20 products...
    ],
  };

  const amazonData = {
    electronics: [
      { id: 1, name: 'IPhone 16', description: 'High-performance smartphone with the latest features.', price: 10200, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=iPhone+16', url: 'https://www.amazon.in' },
      { id: 2, name: 'Samsung Galaxy S23', description: 'Premium smartphone with superior battery life.', price: 85200, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Galaxy+S23', url: 'https://www.amazon.in' },
      { id: 3, name: 'OnePlus Nord CE 3', description: 'Affordable smartphone with advanced features.', price: 29800, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Nord+CE+3', url: 'https://www.amazon.in' },
      { id: 4, name: 'Redmi Note 12', description: 'Efficient smartphone for everyday use.', price: 14800, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Note+12', url: 'https://www.amazon.in' },
      { id: 5, name: 'Realme Narzo 60X', description: 'Gaming smartphone with excellent performance.', price: 18200, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Narzo+60X', url: 'https://www.amazon.in' },
      { id: 6, name: 'Apple AirPods Pro', description: 'Noise-canceling wireless earbuds with premium sound.', price: 25200, rating: 4.8, imageUrl: 'https://via.placeholder.com/150?text=AirPods+Pro', url: 'https://www.amazon.in' },
      { id: 7, name: 'Dell Inspiron 3505', description: 'Lightweight and portable laptop.', price: 44800, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Dell+Inspiron+3505', url: 'https://www.amazon.in' },
      { id: 8, name: 'HP Envy x360', description: 'Convertible laptop with powerful specifications.', price: 79800, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=HP+Envy+x360', url: 'https://www.amazon.in' },
      { id: 9, name: 'Sony WH-1000XM5', description: 'Industry-leading noise-canceling headphones.', price: 29800, rating: 4.9, imageUrl: 'https://via.placeholder.com/150?text=Sony+WH-1000XM5', url: 'https://www.amazon.in' },
      { id: 10, name: 'Samsung Smart TV', description: 'Crystal-clear visuals with a sleek design.', price: 49800, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Samsung+Smart+TV', url: 'https://www.amazon.in' },
    ],
    jewelry: [
      { id: 1, name: 'Gold Necklace', description: 'Elegant gold necklace with intricate patterns.', price: 25200, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Gold+Necklace', url: 'https://www.amazon.in' },
      { id: 2, name: 'Diamond Earrings', description: 'Modern diamond earrings for a sophisticated look.', price: 50200, rating: 4.9, imageUrl: 'https://via.placeholder.com/150?text=Diamond+Earrings', url: 'https://www.amazon.in' },
      { id: 3, name: 'Silver Bracelet', description: 'Everyday wear bracelet with timeless design.', price: 2100, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Silver+Bracelet', url: 'https://www.amazon.in' },
      { id: 4, name: 'Platinum Ring', description: 'Exquisite platinum ring with a solitaire.', price: 60200, rating: 4.8, imageUrl: 'https://via.placeholder.com/150?text=Platinum+Ring', url: 'https://www.amazon.in' },
      { id: 5, name: 'Pearl Necklace', description: 'Elegant necklace for a chic look.', price: 8200, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Pearl+Necklace', url: 'https://www.amazon.in' },
      { id: 6, name: 'Gold Bangles', description: 'Beautifully crafted gold bangles.', price: 30200, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Gold+Bangles', url: 'https://www.amazon.in' },
      { id: 7, name: 'Diamond Pendant', description: 'A pendant that adds sparkle to every outfit.', price: 45200, rating: 4.9, imageUrl: 'https://via.placeholder.com/150?text=Diamond+Pendant', url: 'https://www.amazon.in' },
      { id: 8, name: 'Ruby Ring', description: 'Ruby-studded ring with a stunning design.', price: 22200, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Ruby+Ring', url: 'https://www.amazon.in' },
      { id: 9, name: 'Silver Anklet', description: 'A stylish anklet for daily wear.', price: 1300, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Silver+Anklet', url: 'https://www.amazon.in' },
      { id: 10, name: 'Gold Chain', description: 'Classic chain suitable for every occasion.', price: 15200, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Gold+Chain', url: 'https://www.amazon.in' },
    ],
    men_clothing: [
      { id: 1, name: 'Men\'s Cotton T-Shirt', description: 'Comfortable and stylish cotton t-shirt.', price: 499, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Cotton+T-Shirt', url: 'https://www.amazon.in' },
      { id: 2, name: 'Slim Fit Jeans', description: 'Classic slim-fit jeans for a modern look.', price: 1299, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Slim+Fit+Jeans', url: 'https://www.amazon.in' },
      { id: 3, name: 'Men\'s Casual Shirt', description: 'Lightweight shirt perfect for casual outings.', price: 999, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Casual+Shirt', url: 'https://www.amazon.in' },
      { id: 4, name: 'Formal Suit', description: 'Elegant formal suit for business and events.', price: 5499, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Formal+Suit', url: 'https://www.amazon.in' },
      { id: 5, name: 'Men\'s Hoodie', description: 'Cozy hoodie with a relaxed fit.', price: 1499, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Men\'s+Hoodie', url: 'https://www.amazon.in' },
      { id: 6, name: 'Cargo Pants', description: 'Stylish and functional cargo pants.', price: 1399, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Cargo+Pants', url: 'https://www.amazon.in' },
      { id: 7, name: 'Leather Jacket', description: 'Premium leather jacket for a bold look.', price: 4999, rating: 4.8, imageUrl: 'https://via.placeholder.com/150?text=Leather+Jacket', url: 'https://www.amazon.in' },
      { id: 8, name: 'Track Pants', description: 'Comfortable track pants for sports and leisure.', price: 899, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Track+Pants', url: 'https://www.amazon.in' },
      { id: 9, name: 'Polo T-Shirt', description: 'Classic polo t-shirt with a sporty touch.', price: 749, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Polo+T-Shirt', url: 'https://www.amazon.in' },
      { id: 10, name: 'Men\'s Blazer', description: 'Sophisticated blazer for formal occasions.', price: 3499, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Men\'s+Blazer', url: 'https://www.amazon.in' },
    ],
    women_clothing: [
      { id: 1, name: 'Women\'s Kurti', description: 'Elegant ethnic kurti with beautiful embroidery.', price: 899, rating: 4.5, imageUrl: 'https://m.media-amazon.com/images/I/518+mXFfoUL._AC_UY350_.jpg', url: 'https://www.amazon.in' },
      { id: 2, name: 'Anarkali Dress', description: 'Flowing anarkali dress for festive occasions.', price: 1799, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Anarkali+Dress', url: 'https://www.amazon.in' },
      { id: 3, name: 'Women\'s Jeans', description: 'Stretchable jeans for all-day comfort.', price: 1299, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Women\'s+Jeans', url: 'https://www.amazon.in' },
      { id: 4, name: 'Chiffon Saree', description: 'Lightweight chiffon saree with intricate patterns.', price: 1499, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Chiffon+Saree', url: 'https://www.amazon.in' },
      { id: 5, name: 'Formal Blouse', description: 'Chic blouse for professional settings.', price: 749, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Formal+Blouse', url: 'https://www.amazon.in' },
      { id: 6, name: 'Women\'s Cardigan', description: 'Soft and cozy cardigan for cool weather.', price: 1199, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Women\'s+Cardigan', url: 'https://www.amazon.in' },
      { id: 7, name: 'Maxi Dress', description: 'Stylish and comfortable maxi dress.', price: 1999, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Maxi+Dress', url: 'https://www.amazon.in' },
      { id: 8, name: 'Lehenga Choli', description: 'Traditional lehenga choli with modern design.', price: 3499, rating: 4.8, imageUrl: 'https://via.placeholder.com/150?text=Lehenga+Choli', url: 'https://www.amazon.in' },
      { id: 9, name: 'Cotton Palazzo', description: 'Lightweight palazzo pants for casual wear.', price: 899, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Cotton+Palazzo', url: 'https://www.amazon.in' },
      { id: 10, name: 'Women\'s T-Shirt', description: 'Casual t-shirt for everyday wear.', price: 599, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Women\'s+T-Shirt', url: 'https://www.amazon.in' },
    ],
  };

  const myntraData = {
    electronics: [
      { id: 1, name: 'Bluetooth Earbuds', description: 'Wireless earbuds with noise cancellation.', price: 1999, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Bluetooth+Earbuds', url: 'https://www.myntra.com' },
      { id: 2, name: 'Smartwatch', description: 'Feature-packed smartwatch with health tracking.', price: 2999, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Smartwatch', url: 'https://www.myntra.com' },
      { id: 3, name: 'Portable Speaker', description: 'Compact speaker with powerful sound.', price: 1599, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Portable+Speaker', url: 'https://www.myntra.com' },
      { id: 4, name: 'Power Bank', description: '10,000mAh power bank for on-the-go charging.', price: 1299, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Power+Bank', url: 'https://www.myntra.com' },
      { id: 5, name: 'Gaming Mouse', description: 'Ergonomic gaming mouse with customizable buttons.', price: 1099, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Gaming+Mouse', url: 'https://www.myntra.com' },
      { id: 6, name: 'Wireless Keyboard', description: 'Compact and lightweight wireless keyboard.', price: 1499, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Wireless+Keyboard', url: 'https://www.myntra.com' },
      { id: 7, name: 'Laptop Sleeve', description: 'Durable and stylish laptop sleeve.', price: 799, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Laptop+Sleeve', url: 'https://www.myntra.com' },
      { id: 8, name: 'Fitness Tracker', description: 'Track your daily steps and activities.', price: 2499, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Fitness+Tracker', url: 'https://www.myntra.com' },
      { id: 9, name: 'Webcam', description: 'High-definition webcam for video calls.', price: 1699, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Webcam', url: 'https://www.myntra.com' },
      { id: 10, name: 'USB Hub', description: 'Multi-port USB hub for efficient connectivity.', price: 599, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=USB+Hub', url: 'https://www.myntra.com' },
    ],
    jewelry: [
      { id: 1, name: 'Gold-Plated Necklace', description: 'Elegant gold-plated necklace for parties.', price: 1299, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Gold-Plated+Necklace', url: 'https://www.myntra.com' },
      { id: 2, name: 'Diamond Stud Earrings', description: 'Shiny diamond studs with a minimal design.', price: 3999, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Diamond+Stud+Earrings', url: 'https://www.myntra.com' },
      { id: 3, name: 'Pearl Bracelet', description: 'Graceful pearl bracelet with an adjustable fit.', price: 999, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Pearl+Bracelet', url: 'https://www.myntra.com' },
      { id: 4, name: 'Silver Ring', description: 'Sterling silver ring with intricate patterns.', price: 899, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Silver+Ring', url: 'https://www.myntra.com' },
      { id: 5, name: 'Charm Anklet', description: 'Trendy anklet with decorative charms.', price: 799, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Charm+Anklet', url: 'https://www.myntra.com' },
      { id: 6, name: 'Beaded Necklace', description: 'Handcrafted beaded necklace with vibrant colors.', price: 699, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Beaded+Necklace', url: 'https://www.myntra.com' },
      { id: 7, name: 'Gold Bangles', description: 'Set of gold-plated bangles for a traditional look.', price: 1499, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Gold+Bangles', url: 'https://www.myntra.com' },
      { id: 8, name: 'Studded Earrings', description: 'Beautiful earrings studded with colorful stones.', price: 999, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Studded+Earrings', url: 'https://www.myntra.com' },
      { id: 9, name: 'Pendant Chain', description: 'Simple pendant chain for everyday wear.', price: 599, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Pendant+Chain', url: 'https://www.myntra.com' },
      { id: 10, name: 'Nose Ring', description: 'Traditional nose ring with a modern twist.', price: 499, rating: 4.1, imageUrl: 'https://via.placeholder.com/150?text=Nose+Ring', url: 'https://www.myntra.com' },
    ],
    men_clothing: [
      { id: 1, name: 'Casual Shirt', description: 'Trendy casual shirt with a slim fit.', price: 799, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Casual+Shirt', url: 'https://www.myntra.com' },
      { id: 2, name: 'Denim Jeans', description: 'Classic denim jeans for a rugged look.', price: 1199, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Denim+Jeans', url: 'https://www.myntra.com' },
      { id: 3, name: 'Solid Polo T-Shirt', description: 'Stylish polo t-shirt with a solid color.', price: 699, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Solid+Polo+T-Shirt', url: 'https://www.myntra.com' },
      { id: 4, name: 'Formal Trousers', description: 'Elegant trousers for office wear.', price: 1399, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Formal+Trousers', url: 'https://www.myntra.com' },
      { id: 5, name: 'Winter Jacket', description: 'Warm and durable jacket for cold weather.', price: 2499, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Winter+Jacket', url: 'https://www.myntra.com' },
      { id: 6, name: 'Chinos', description: 'Stylish chinos for casual and formal settings.', price: 999, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Chinos', url: 'https://www.myntra.com' },
      { id: 7, name: 'Men\'s Kurta', description: 'Ethnic kurta for festive occasions.', price: 1499, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Men\'s+Kurta', url: 'https://www.myntra.com' },
      { id: 8, name: 'Graphic T-Shirt', description: 'Cool graphic t-shirt with bold prints.', price: 899, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Graphic+T-Shirt', url: 'https://www.myntra.com' },
      { id: 9, name: 'Track Pants', description: 'Comfortable track pants for workouts.', price: 1099, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Track+Pants', url: 'https://www.myntra.com' },
      { id: 10, name: 'Sports Shorts', description: 'Breathable shorts for active wear.', price: 599, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Sports+Shorts', url: 'https://www.myntra.com' },
    ],
    women_clothing: [
      { id: 1, name: 'Floral Maxi Dress', description: 'Beautiful floral maxi dress for summer.', price: 1499, rating: 4.6, imageUrl: 'https://m.media-amazon.com/images/I/518+mXFfoUL._AC_UY350_.jpg', url: 'https://www.myntra.com' },
      { id: 2, name: 'A-Line Kurti', description: 'Elegant A-line kurta with intricate designs.', price: 999, rating: 4.5, imageUrl: 'https://m.media-amazon.com/images/I/518+mXFfoUL._AC_UY350_.jpg', url: 'https://www.myntra.com' },
      { id: 3, name: 'Skinny Fit Jeans', description: 'Stylish and stretchable skinny jeans.', price: 1199, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Skinny+Fit+Jeans', url: 'https://www.myntra.com' },
      { id: 4, name: 'Lehenga Set', description: 'Traditional lehenga with modern patterns.', price: 3999, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Lehenga+Set', url: 'https://www.myntra.com' },
      { id: 5, name: 'Chiffon Dupatta', description: 'Lightweight chiffon dupatta with delicate embroidery.', price: 499, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Chiffon+Dupatta', url: 'https://www.myntra.com' },
      { id: 6, name: 'Bodycon Dress', description: 'Sleek bodycon dress for a bold look.', price: 1699, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Bodycon+Dress', url: 'https://www.myntra.com' },
      { id: 7, name: 'Palazzo Pants', description: 'Comfortable and stylish palazzo pants.', price: 799, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Palazzo+Pants', url: 'https://www.myntra.com' },
      { id: 8, name: 'Crop Top', description: 'Trendy crop top with a modern design.', price: 599, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Crop+Top', url: 'https://www.myntra.com' },
      { id: 9, name: 'Silk Saree', description: 'Luxurious silk saree with traditional motifs.', price: 2499, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Silk+Saree', url: 'https://www.myntra.com' },
      { id: 10, name: 'Women\'s Hoodie', description: 'Cozy hoodie with a relaxed fit.', price: 1299, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Women\'s+Hoodie', url: 'https://www.myntra.com' },
    ],
  };
  
  const meeshoData = {
    electronics: [
      { id: 1, name: 'Wireless Earbuds', description: 'Bluetooth-enabled earbuds with immersive sound.', price: 1499, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Wireless+Earbuds', url: 'https://www.meesho.com' },
      { id: 2, name: 'Smart LED Bulb', description: 'Color-changing smart bulb with app control.', price: 799, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Smart+LED+Bulb', url: 'https://www.meesho.com' },
      { id: 3, name: 'Portable Charger', description: 'Compact power bank with fast charging support.', price: 1299, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Portable+Charger', url: 'https://www.meesho.com' },
      { id: 4, name: 'Noise-Canceling Headphones', description: 'Over-ear headphones with deep bass.', price: 1999, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Noise-Canceling+Headphones', url: 'https://www.meesho.com' },
      { id: 5, name: 'Smartphone Holder', description: 'Adjustable stand for smartphones.', price: 599, rating: 4.1, imageUrl: 'https://via.placeholder.com/150?text=Smartphone+Holder', url: 'https://www.meesho.com' },
      { id: 6, name: 'USB Flash Drive', description: '64GB high-speed pen drive.', price: 899, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=USB+Flash+Drive', url: 'https://www.meesho.com' },
      { id: 7, name: 'Tripod Stand', description: 'Lightweight tripod for cameras and smartphones.', price: 1199, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Tripod+Stand', url: 'https://www.meesho.com' },
      { id: 8, name: 'Bluetooth Speaker', description: 'Portable speaker with long battery life.', price: 1699, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Bluetooth+Speaker', url: 'https://www.meesho.com' },
      { id: 9, name: 'Gaming Keyboard', description: 'Backlit keyboard for gamers.', price: 1799, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Gaming+Keyboard', url: 'https://www.meesho.com' },
      { id: 10, name: 'LED Monitor', description: '22-inch full HD monitor for work and entertainment.', price: 7499, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=LED+Monitor', url: 'https://www.meesho.com' },
    ],
    jewelry: [
      { id: 1, name: 'Kundan Necklace Set', description: 'Traditional Kundan jewelry with earrings.', price: 1199, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Kundan+Necklace+Set', url: 'https://www.meesho.com' },
      { id: 2, name: 'Gold Plated Bangles', description: 'Beautiful gold-plated bangles for a traditional look.', price: 899, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Gold+Plated+Bangles', url: 'https://www.meesho.com' },
      { id: 3, name: 'Pearl Earrings', description: 'Delicate pearl earrings for casual and formal wear.', price: 499, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Pearl+Earrings', url: 'https://www.meesho.com' },
      { id: 4, name: 'Silver Pendant Set', description: 'Elegant silver pendant with matching earrings.', price: 799, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Silver+Pendant+Set', url: 'https://www.meesho.com' },
      { id: 5, name: 'Bridal Jewelry Set', description: 'Complete bridal set with necklace, earrings, and maang tikka.', price: 2499, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Bridal+Jewelry+Set', url: 'https://www.meesho.com' },
      { id: 6, name: 'Stone Studded Anklets', description: 'Modern anklets with colorful stones.', price: 599, rating: 4.1, imageUrl: 'https://via.placeholder.com/150?text=Stone+Studded+Anklets', url: 'https://www.meesho.com' },
      { id: 7, name: 'Choker Necklace', description: 'Trendy choker necklace for party wear.', price: 999, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Choker+Necklace', url: 'https://www.meesho.com' },
      { id: 8, name: 'Oxidized Jewelry Set', description: 'Traditional oxidized necklace and earrings.', price: 799, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Oxidized+Jewelry+Set', url: 'https://www.meesho.com' },
      { id: 9, name: 'Diamond Bracelet', description: 'Artificial diamond bracelet with a modern design.', price: 1499, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Diamond+Bracelet', url: 'https://www.meesho.com' },
      { id: 10, name: 'Nose Pin Set', description: 'Set of 5 decorative nose pins.', price: 399, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Nose+Pin+Set', url: 'https://www.meesho.com' },
    ],
    men_clothing: [
      { id: 1, name: 'Casual Cotton Shirt', description: 'Stylish and comfortable cotton shirt.', price: 899, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Casual+Cotton+Shirt', url: 'https://www.meesho.com' },
      { id: 2, name: 'Formal Trousers', description: 'Elegant trousers perfect for office wear.', price: 1199, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Formal+Trousers', url: 'https://www.meesho.com' },
      { id: 3, name: 'Denim Jeans', description: 'Regular fit denim jeans for daily wear.', price: 1399, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Denim+Jeans', url: 'https://www.meesho.com' },
      { id: 4, name: 'Printed T-Shirt', description: 'Trendy printed T-shirt for casual outings.', price: 699, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Printed+T-Shirt', url: 'https://www.meesho.com' },
      { id: 5, name: 'Hooded Sweatshirt', description: 'Comfortable hoodie for cool weather.', price: 1499, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Hooded+Sweatshirt', url: 'https://www.meesho.com' },
      { id: 6, name: 'Ethnic Kurta', description: 'Traditional kurta with intricate designs.', price: 1199, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Ethnic+Kurta', url: 'https://www.meesho.com' },
      { id: 7, name: 'Track Pants', description: 'Comfortable track pants for gym or home.', price: 799, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Track+Pants', url: 'https://www.meesho.com' },
      { id: 8, name: 'Blazer', description: 'Formal blazer for special occasions.', price: 2499, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Blazer', url: 'https://www.meesho.com' },
      { id: 9, name: 'Shorts', description: 'Casual shorts for summer days.', price: 599, rating: 4.1, imageUrl: 'https://via.placeholder.com/150?text=Shorts', url: 'https://www.meesho.com' },
      { id: 10, name: 'Leather Jacket', description: 'Trendy leather jacket for a bold look.', price: 3499, rating: 4.8, imageUrl: 'https://via.placeholder.com/150?text=Leather+Jacket', url: 'https://www.meesho.com' },
    ],
    women_clothing: [
      { id: 1, name: 'Floral Maxi Dress', description: 'Beautiful maxi dress with floral patterns.', price: 1299, rating: 4.5, imageUrl: 'https://via.placeholder.com/150?text=Floral+Maxi+Dress', url: 'https://www.meesho.com' },
      { id: 2, name: 'Silk Saree', description: 'Elegant silk saree with intricate embroidery.', price: 2499, rating: 4.7, imageUrl: 'https://via.placeholder.com/150?text=Silk+Saree', url: 'https://www.meesho.com' },
      { id: 3, name: 'Anarkali Suit', description: 'Designer Anarkali suit for festive occasions.', price: 1999, rating: 4.6, imageUrl: 'https://via.placeholder.com/150?text=Anarkali+Suit', url: 'https://www.meesho.com' },
      { id: 4, name: 'Denim Jacket', description: 'Trendy denim jacket for a casual look.', price: 1499, rating: 4.4, imageUrl: 'https://via.placeholder.com/150?text=Denim+Jacket', url: 'https://www.meesho.com' },
      { id: 5, name: 'Leggings', description: 'Comfortable leggings for everyday wear.', price: 499, rating: 4.2, imageUrl: 'https://via.placeholder.com/150?text=Leggings', url: 'https://www.meesho.com' },
      { id: 6, name: 'Palazzo Pants', description: 'Stylish palazzo pants for a chic look.', price: 899, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Palazzo+Pants', url: 'https://www.meesho.com' },
      { id: 7, name: 'Kurti', description: 'Designer kurti with a modern twist.', price: 1299, rating: 4.6, imageUrl: 'https://m.media-amazon.com/images/I/518+mXFfoUL._AC_UY350_.jpg', url: 'https://www.meesho.com' },
      { id: 8, name: 'Crop Top', description: 'Trendy crop top for parties.', price: 799, rating: 4.1, imageUrl: 'https://via.placeholder.com/150?text=Crop+Top', url: 'https://www.meesho.com' },
      { id: 9, name: 'Chiffon Dupatta', description: 'Lightweight chiffon dupatta for ethnic outfits.', price: 399, rating: 4.3, imageUrl: 'https://via.placeholder.com/150?text=Chiffon+Dupatta', url: 'https://www.meesho.com' },
      { id: 10, name: 'Evening Gown', description: 'Elegant evening gown with sequins.', price: 2999, rating: 4.8, imageUrl: 'https://via.placeholder.com/150?text=Evening+Gown', url: 'https://www.meesho.com' },
    ],
  };

module.exports = { flipkartData, amazonData, myntraData, meeshoData };
